-- =============================================================================
-- Migration: Create UserColumnPreferences table
-- Apply this to your PostgreSQL database (local, Supabase, Render, etc.).
-- Safe to run multiple times — uses IF NOT EXISTS guards.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "UserColumnPreferences" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"      integer NOT NULL,
    "TableKey"    character varying(100) NOT NULL,
    "ColumnsJson" text NOT NULL DEFAULT '{}',
    "UpdatedAt"   timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_UserColumnPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserColumnPreferences_Users_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

-- Unique index to ensure one preference record per user per table
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserColumnPreferences_UserId_TableKey"
    ON "UserColumnPreferences" ("UserId", "TableKey");

COMMIT;
