-- Add soft delete columns to all main tables
-- IsDeleted: flag marking the record as deleted
-- DeletedOn: timestamp when the record was soft-deleted
-- DeletedById: FK to Users table (who deleted the record)

ALTER TABLE "Users"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Vehicles"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Roles"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Permissions"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Materials"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Vendors"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Projects"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Fuels"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "FuelLogs"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "DozerLogs"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Transportations"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "SalarySetups"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "MonthlySalaries"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "SalaryPayments"
    ADD COLUMN IF NOT EXISTS "IsDeleted"   BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "DeletedOn"   TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS "DeletedById" INT         NULL REFERENCES "Users"("Id") ON DELETE SET NULL;
