-- =============================================================
-- CMS — Add Vehicles table
--
-- Run this against the existing "cms" database.
--
-- Option A — psql:
--   psql -U postgres -d cms -f database/add_vehicles_table.sql
--
-- Option B — pgAdmin:
--   Open Query Tool on the "cms" database and run this script.
-- =============================================================

CREATE TABLE IF NOT EXISTS "Vehicles" (
    "Id"           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "NumberPlate"  VARCHAR(20)  NOT NULL,
    "Type"         VARCHAR(20)  NOT NULL,
    "CreatedAt"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMP WITH TIME ZONE NULL,

    CONSTRAINT "CK_Vehicles_Type" CHECK ("Type" IN ('Tipper', 'Jcb'))
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Vehicles_NumberPlate" ON "Vehicles" ("NumberPlate");
