ALTER TABLE "Transportations"
    ADD COLUMN IF NOT EXISTS "Location" VARCHAR(200),
    ADD COLUMN IF NOT EXISTS "PartyNameId" INT NULL REFERENCES "PartyNames"("Id") ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS "NoOfTip" INT NULL;


