-- =============================================================
-- CMS Full Schema — PostgreSQL / Supabase
-- Run this on a fresh database (drops everything first).
-- =============================================================

-- -------------------------------------------------------------
-- Drop all tables (reverse-dependency order)
-- -------------------------------------------------------------
DROP TABLE IF EXISTS "SalaryDetails"   CASCADE;
DROP TABLE IF EXISTS "SalaryPayments"  CASCADE;
DROP TABLE IF EXISTS "MonthlySalaries" CASCADE;
DROP TABLE IF EXISTS "SalarySetups"    CASCADE;
DROP TABLE IF EXISTS "ErrorLogs"       CASCADE;
DROP TABLE IF EXISTS "DozerLogs"       CASCADE;
DROP TABLE IF EXISTS "FuelLogs"        CASCADE;
DROP TABLE IF EXISTS "Transportations" CASCADE;
DROP TABLE IF EXISTS "ExtraExpenses"   CASCADE;
DROP TABLE IF EXISTS "BankAccountDebitLogs" CASCADE;
DROP TABLE IF EXISTS "PartyBalanceLogs" CASCADE;
DROP TABLE IF EXISTS "VendorBalanceLogs" CASCADE;
DROP TABLE IF EXISTS "BankAccountCreditLogs" CASCADE;
DROP TABLE IF EXISTS "BankAccounts"    CASCADE;
DROP TABLE IF EXISTS "RolePermissions" CASCADE;
DROP TABLE IF EXISTS "Permissions"     CASCADE;
DROP TABLE IF EXISTS "Materials"       CASCADE;
DROP TABLE IF EXISTS "Vendors"         CASCADE;
DROP TABLE IF EXISTS "Projects"        CASCADE;
DROP TABLE IF EXISTS "Fuels"           CASCADE;
DROP TABLE IF EXISTS "Users"           CASCADE;
DROP TABLE IF EXISTS "Vehicles"        CASCADE;
DROP TABLE IF EXISTS "Roles"           CASCADE;

-- -------------------------------------------------------------
-- Roles  (no dependencies)
-- -------------------------------------------------------------
CREATE TABLE "Roles" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT,
    "UpdatedById"  INT,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT
);

-- -------------------------------------------------------------
-- Vehicles  (CreatedById/UpdatedById FKs added after Users)
-- -------------------------------------------------------------
CREATE TABLE "Vehicles" (
    "Id"           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "NumberPlate"  VARCHAR(20)  NOT NULL,
    "Type"         VARCHAR(20)  NOT NULL CHECK ("Type" IN ('Tipper', 'Jcb', 'Nissan')),
    "Ownership"    VARCHAR(20)  NOT NULL DEFAULT 'Owned' CHECK ("Ownership" IN ('Owned', 'Partnered')),
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT,
    "UpdatedById"  INT,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT,
    CONSTRAINT "UX_Vehicles_NumberPlate" UNIQUE ("NumberPlate")
);

-- -------------------------------------------------------------
-- Users
-- -------------------------------------------------------------
CREATE TABLE "Users" (
    "Id"            SERIAL       PRIMARY KEY,
    "Username"      VARCHAR(50)  NOT NULL,
    "Email"         VARCHAR(256) NOT NULL,
    "PasswordHash"  VARCHAR(500) NOT NULL,
    "FirstName"     VARCHAR(100),
    "LastName"      VARCHAR(100),
    "IsActive"      BOOLEAN      NOT NULL DEFAULT TRUE,
    "CreatedAt"     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ,
    "LastLoginAt"   TIMESTAMPTZ,
    "RoleId"        INT          REFERENCES "Roles"("Id")    ON DELETE SET NULL,
    "VehicleId"     INT,
    "CreatedById"   INT,
    "UpdatedById"   INT,
    "IsDeleted"     BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"     TIMESTAMPTZ,
    "DeletedById"   INT,
    CONSTRAINT "UX_Users_Username" UNIQUE ("Username"),
    CONSTRAINT "UX_Users_Email"    UNIQUE ("Email")
);

-- Cross-table FKs now that both Vehicles and Users exist
ALTER TABLE "Users"
    ADD CONSTRAINT "FK_Users_VehicleId"    FOREIGN KEY ("VehicleId")    REFERENCES "Vehicles"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Users_CreatedById"  FOREIGN KEY ("CreatedById")   REFERENCES "Users"("Id")    ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Users_UpdatedById"  FOREIGN KEY ("UpdatedById")   REFERENCES "Users"("Id")    ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Users_DeletedById"  FOREIGN KEY ("DeletedById")   REFERENCES "Users"("Id")    ON DELETE SET NULL;

ALTER TABLE "Vehicles"
    ADD CONSTRAINT "FK_Vehicles_CreatedById"  FOREIGN KEY ("CreatedById")  REFERENCES "Users"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Vehicles_UpdatedById"  FOREIGN KEY ("UpdatedById")  REFERENCES "Users"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Vehicles_DeletedById"  FOREIGN KEY ("DeletedById")  REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Roles"
    ADD CONSTRAINT "FK_Roles_CreatedById"  FOREIGN KEY ("CreatedById")  REFERENCES "Users"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Roles_UpdatedById"  FOREIGN KEY ("UpdatedById")  REFERENCES "Users"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Roles_DeletedById"  FOREIGN KEY ("DeletedById")  REFERENCES "Users"("Id") ON DELETE SET NULL;

-- -------------------------------------------------------------
-- Materials
-- -------------------------------------------------------------
CREATE TABLE "Materials" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Vendors
-- -------------------------------------------------------------
CREATE TABLE "Vendors" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "PanNumber"    VARCHAR(20),
    "TotalBalance" NUMERIC(18, 2) NOT NULL DEFAULT 0,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Government Offices
-- -------------------------------------------------------------
CREATE TABLE "GovernmentOffices" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(200) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Maintenance Parts
-- -------------------------------------------------------------
CREATE TABLE "MaintenanceParts" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(300) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Party Names
-- -------------------------------------------------------------
CREATE TABLE "PartyNames" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(200) NOT NULL,
    "Type"         VARCHAR(50)  NOT NULL DEFAULT 'other',
    "Address"      VARCHAR(500),
    "TotalBalance" NUMERIC(18, 2) NOT NULL DEFAULT 0,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Projects
-- -------------------------------------------------------------
CREATE TABLE "Projects" (
    "Id"             SERIAL       PRIMARY KEY,
    "Name"           VARCHAR(200) NOT NULL,
    "Address"        VARCHAR(500),
    "IssuedOfficeId" INT REFERENCES "GovernmentOffices"("Id") ON DELETE SET NULL,
    "StartDate"      DATE,
    "EndDate"        DATE,
    "ProjectCost"    NUMERIC(18, 2),
    "CreatedAt"      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"      TIMESTAMPTZ,
    "CreatedById"    INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"    INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"      BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"      TIMESTAMPTZ,
    "DeletedById"    INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Project Commissions
-- -------------------------------------------------------------
CREATE TABLE "ProjectCommissions" (
    "Id"           SERIAL          PRIMARY KEY,
    "ProjectId"    INT             NOT NULL REFERENCES "Projects"("Id") ON DELETE CASCADE,
    "OfficeId"     INT             REFERENCES "GovernmentOffices"("Id") ON DELETE SET NULL,
    "OtherOption"  VARCHAR(200),
    "Amount"       NUMERIC(18, 2)  NOT NULL,
    "Remarks"      VARCHAR(500),
    "CreatedAt"    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Project Expenses
-- -------------------------------------------------------------
CREATE TABLE "ProjectExpenses" (
    "Id"           SERIAL          PRIMARY KEY,
    "ProjectId"    INT             NOT NULL REFERENCES "Projects"("Id") ON DELETE CASCADE,
    "MaterialId"   INT             REFERENCES "Materials"("Id") ON DELETE SET NULL,
    "Quantity"     NUMERIC(18, 2),
    "CostPerUnit"  NUMERIC(18, 2),
    "TotalCost"    NUMERIC(18, 2),
    "VendorId"     INT             REFERENCES "Vendors"("Id") ON DELETE SET NULL,
    "VendorOther"  VARCHAR(200),
    "Date"         DATE            NOT NULL,
    "Remarks"      VARCHAR(500),
    "CreatedAt"    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Project Wages
-- -------------------------------------------------------------
CREATE TABLE "ProjectWages" (
    "Id"                SERIAL          PRIMARY KEY,
    "ProjectId"         INT             NOT NULL REFERENCES "Projects"("Id") ON DELETE CASCADE,
    "NumberOfWorkers"   INT             NOT NULL,
    "Rate"              NUMERIC(18, 2)  NOT NULL,
    "TotalAmount"       NUMERIC(18, 2)  NOT NULL,
    "Date"              DATE            NOT NULL,
    "Remarks"           VARCHAR(500),
    "CreatedAt"         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"         TIMESTAMPTZ,
    "CreatedById"       INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"       INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"         BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"         TIMESTAMPTZ,
    "DeletedById"       INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Vehicle Maintenance Logs
-- -------------------------------------------------------------
CREATE TABLE "VehicleMaintenanceLogs" (
    "Id"           SERIAL       PRIMARY KEY,
    "VehicleId"    INT          NOT NULL REFERENCES "Vehicles"("Id") ON DELETE CASCADE,
    "Date"         DATE         NOT NULL,
    "Remarks"      VARCHAR(500),
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Vehicle Maintenance Parts
-- -------------------------------------------------------------
CREATE TABLE "VehicleMaintenanceParts" (
    "Id"                 SERIAL          PRIMARY KEY,
    "MaintenanceLogId"   INT             NOT NULL REFERENCES "VehicleMaintenanceLogs"("Id") ON DELETE CASCADE,
    "MaintenancePartId"  INT             NOT NULL REFERENCES "MaintenanceParts"("Id") ON DELETE RESTRICT,
    "Quantity"           NUMERIC(18, 2),
    "UnitCost"           NUMERIC(18, 2),
    "TotalCost"          NUMERIC(18, 2),
    "Remarks"            VARCHAR(500),
    "CreatedAt"          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"          TIMESTAMPTZ,
    "CreatedById"        INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"        INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"          BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"          TIMESTAMPTZ,
    "DeletedById"        INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Vehicle Maintenance Wages
-- -------------------------------------------------------------
CREATE TABLE "VehicleMaintenanceWages" (
    "Id"                SERIAL          PRIMARY KEY,
    "MaintenanceLogId"  INT             NOT NULL REFERENCES "VehicleMaintenanceLogs"("Id") ON DELETE CASCADE,
    "NumberOfWorkers"   INT             NOT NULL,
    "Rate"              NUMERIC(18, 2)  NOT NULL,
    "TotalAmount"       NUMERIC(18, 2)  NOT NULL,
    "Remarks"           VARCHAR(500),
    "CreatedAt"         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"         TIMESTAMPTZ,
    "CreatedById"       INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"       INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"         BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"         TIMESTAMPTZ,
    "DeletedById"       INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Fuels (fuel types)
-- -------------------------------------------------------------
CREATE TABLE "Fuels" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN      NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Transportations
-- -------------------------------------------------------------
CREATE TABLE "Transportations" (
    "Id"                  SERIAL          PRIMARY KEY,
    -- Either TransportedById (FK) or TransportedByOther (free text) must be set
    "TransportedById"     INT             REFERENCES "Users"("Id")           ON DELETE SET NULL,
    "TransportedByOther"  VARCHAR(200),
    "VehicleId"           INT             REFERENCES "Vehicles"("Id")        ON DELETE SET NULL,
    "VehicleOther"        VARCHAR(200),
    "MaterialId"          INT             REFERENCES "Materials"("Id")       ON DELETE SET NULL,
    "VendorId"            INT             REFERENCES "Vendors"("Id")         ON DELETE SET NULL,
    "VendorOther"         VARCHAR(200),
    "ProjectId"           INT             REFERENCES "Projects"("Id")        ON DELETE SET NULL,
    "ProjectOther"        VARCHAR(200),
    "Location"            VARCHAR(200),
    "PartyNameId"         INT REFERENCES "PartyNames"("Id") ON DELETE SET NULL,
    "NoOfTip"             INT,
    "Quantity"            NUMERIC(18, 2),
    "PerUnitCost"         NUMERIC(18, 2),
    "MaterialCost"        NUMERIC(18, 2),
    "Tax"                 NUMERIC(18, 2),
    "Wages"               NUMERIC(18, 2),
    "TotalWages"          NUMERIC(18, 2),
    "Date"                DATE            NOT NULL,
    "CreatedAt"           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"           TIMESTAMPTZ,
    "CreatedById"         INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"         INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"           BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"           TIMESTAMPTZ,
    "DeletedById"         INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "chk_transporter" CHECK (("TransportedById" IS NOT NULL) <> ("TransportedByOther" IS NOT NULL)),
    CONSTRAINT "chk_vendor"      CHECK (("VendorId"        IS NOT NULL) <> ("VendorOther"        IS NOT NULL)),
    CONSTRAINT "chk_project_reference" CHECK (
        "PartyNameId" IS NOT NULL
        OR
        (("ProjectId" IS NOT NULL) <> ("ProjectOther" IS NOT NULL))
    )
);

-- -------------------------------------------------------------
-- FuelLogs
-- -------------------------------------------------------------
CREATE TABLE "FuelLogs" (
    "Id"             SERIAL          PRIMARY KEY,
    "DriverId"       INT             NOT NULL REFERENCES "Users"("Id")    ON DELETE RESTRICT,
    "VehicleId"      INT             NOT NULL REFERENCES "Vehicles"("Id") ON DELETE RESTRICT,
    "FuelTypeId"     INT             NOT NULL REFERENCES "Fuels"("Id")    ON DELETE RESTRICT,
    "PartyNameId"    INT             REFERENCES "PartyNames"("Id")        ON DELETE SET NULL,
    "PartyNameOther" VARCHAR(200),
    "Quantity"       NUMERIC(10, 2)  NOT NULL CHECK ("Quantity" > 0),
    "Price"          NUMERIC(10, 2)  NOT NULL CHECK ("Price" > 0),
    "Date"           DATE            NOT NULL,
    "CreatedAt"      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"      TIMESTAMPTZ,
    "CreatedById"    INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"    INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"      BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"      TIMESTAMPTZ,
    "DeletedById"    INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_FuelLogs_PartyNameId"
ON "FuelLogs" ("PartyNameId");

-- -------------------------------------------------------------
-- DozerLogs
-- -------------------------------------------------------------
CREATE TABLE "DozerLogs" (
    "Id"              SERIAL         PRIMARY KEY,
    "DriverId"        INT            NOT NULL REFERENCES "Users"("Id")    ON DELETE RESTRICT,
    "VehicleId"       INT            REFERENCES "Vehicles"("Id")          ON DELETE SET NULL,
    "OperationDate"   DATE           NOT NULL,
    "OperatedTimeMs"  INT            CHECK ("OperatedTimeMs" >= 0),
    "StartMeter"      NUMERIC(10,2)  NOT NULL CHECK ("StartMeter" >= 0),
    "EndMeter"        NUMERIC(10,2)  NOT NULL CHECK ("EndMeter" > "StartMeter" OR ("StartMeter" = 0 AND "EndMeter" = 0)),
    "TotalMeterRun"   NUMERIC(10,2)  NOT NULL DEFAULT 0,
    "ProjectId"       INT            REFERENCES "Projects"("Id")          ON DELETE SET NULL,
    "ProjectOther"    VARCHAR(200),
    "Wages"           NUMERIC(12, 2),
    "PartyNameId"     INT            REFERENCES "PartyNames"("Id")        ON DELETE SET NULL,
    "Location"        VARCHAR(200),
    "PaymentType"     VARCHAR(20)    CHECK ("PaymentType" IN ('Cash', 'Credit')),
    "CashAmount"      NUMERIC(12,2)  CHECK ("CashAmount" >= 0),
    "WorkOrderBy"     VARCHAR(200),
    "CreatedAt"       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    "UpdatedAt"       TIMESTAMPTZ,
    "CreatedById"     INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"     INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"       BOOLEAN        NOT NULL DEFAULT FALSE,
    "DeletedOn"       TIMESTAMPTZ,
    "DeletedById"     INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "chk_dozer_project" CHECK (
        ("PartyNameId" IS NULL AND "ProjectId" IS NULL AND "ProjectOther" IS NULL) OR
        ("PartyNameId" IS NOT NULL AND "ProjectId" IS NULL AND "ProjectOther" IS NULL) OR
        ("PartyNameId" IS NULL AND (("ProjectId" IS NOT NULL) <> ("ProjectOther" IS NOT NULL)))
    )
);

-- -------------------------------------------------------------
-- ErrorLogs
-- -------------------------------------------------------------
CREATE TABLE "ErrorLogs" (
    "Id"            SERIAL          PRIMARY KEY,
    "Message"       TEXT            NOT NULL,
    "ExceptionType" VARCHAR(250),
    "StackTrace"    TEXT,
    "Source"        VARCHAR(250),
    "RequestPath"   VARCHAR(500),
    "RequestMethod" VARCHAR(10),
    "QueryString"   VARCHAR(1000),
    "StatusCode"    INT             NOT NULL DEFAULT 500,
    "UserAgent"     VARCHAR(500),
    "ClientIp"      VARCHAR(50),
    "UserId"        INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "CreatedAt"     TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "IX_ErrorLogs_CreatedAt" ON "ErrorLogs" ("CreatedAt" DESC);

-- -------------------------------------------------------------
-- Permissions
-- -------------------------------------------------------------
CREATE TABLE "Permissions" (
    "Id"           SERIAL        PRIMARY KEY,
    "Name"         VARCHAR(100)  NOT NULL,
    "Description"  VARCHAR(255),
    "CreatedAt"    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"    BOOLEAN       NOT NULL DEFAULT FALSE,
    "DeletedOn"    TIMESTAMPTZ,
    "DeletedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "UX_Permissions_Name" UNIQUE ("Name")
);

-- -------------------------------------------------------------
-- RolePermissions  (junction)
-- -------------------------------------------------------------
CREATE TABLE "RolePermissions" (
    "Id"            SERIAL  PRIMARY KEY,
    "RoleId"        INT     NOT NULL REFERENCES "Roles"("Id")       ON DELETE CASCADE,
    "PermissionId"  INT     NOT NULL REFERENCES "Permissions"("Id") ON DELETE CASCADE,
    CONSTRAINT "UX_RolePermissions_RoleId_PermissionId" UNIQUE ("RoleId", "PermissionId")
);

-- -------------------------------------------------------------
-- SalarySetups
-- -------------------------------------------------------------
CREATE TABLE "SalarySetups" (
    "Id"             SERIAL          PRIMARY KEY,
    "UserId"         INT             NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "MonthlySalary"  NUMERIC(12, 2)  NOT NULL,
    "CreatedAt"      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"      TIMESTAMPTZ,
    "CreatedById"    INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"    INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"      BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"      TIMESTAMPTZ,
    "DeletedById"    INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "UX_SalarySetups_UserId" UNIQUE ("UserId")
);

-- -------------------------------------------------------------
-- MonthlySalaries
-- -------------------------------------------------------------
CREATE TABLE "MonthlySalaries" (
    "Id"          SERIAL          PRIMARY KEY,
    "UserId"      INT             NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Month"       SMALLINT        NOT NULL CHECK ("Month" BETWEEN 1 AND 12),
    "Year"        SMALLINT        NOT NULL,
    "Amount"      NUMERIC(12, 2)  NOT NULL,
    "IsVerified"  BOOLEAN         NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"   TIMESTAMPTZ,
    "CreatedById" INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById" INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"   BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"   TIMESTAMPTZ,
    "DeletedById" INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "UX_MonthlySalaries_UserId_Month_Year" UNIQUE ("UserId", "Month", "Year")
);

-- -------------------------------------------------------------
-- SalaryPayments
-- -------------------------------------------------------------
CREATE TABLE "SalaryPayments" (
    "Id"          SERIAL          PRIMARY KEY,
    "UserId"      INT             NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Amount"      NUMERIC(12, 2)  NOT NULL,
    "PaidOn"      DATE            NOT NULL,
    "Remarks"     TEXT,
    "CreatedAt"   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"   TIMESTAMPTZ,
    "CreatedById" INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById" INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"   BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"   TIMESTAMPTZ,
    "DeletedById" INT             REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- SalaryDetails  (one row per employee, auto-maintained)
-- -------------------------------------------------------------
CREATE TABLE "SalaryDetails" (
    "Id"          SERIAL          PRIMARY KEY,
    "UserId"      INT             NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "TotalSalary" NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    "Paid"        NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    "Remaining"   NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    CONSTRAINT "UX_SalaryDetails_UserId" UNIQUE ("UserId")
);

-- -------------------------------------------------------------
-- ExtraExpenses
-- -------------------------------------------------------------
CREATE TABLE "ExtraExpenses" (
    "Id"              SERIAL          PRIMARY KEY,
    "ExpensedById"    INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "ExpensedByOther" VARCHAR(200),
    "Item"            VARCHAR(200)    NOT NULL,
    "Quantity"        NUMERIC(18, 2),
    "Cost"            NUMERIC(18, 2),
    "TotalCost"       NUMERIC(18, 2)  NOT NULL,
    "Remarks"         VARCHAR(500),
    "IsVerified"      BOOLEAN         NOT NULL DEFAULT FALSE,
    "VerifiedById"    INT             REFERENCES "Users"("Id") ON DELETE SET NULL,
    "VerifiedAt"      TIMESTAMPTZ,
    "Date"            DATE            NOT NULL,
    "CreatedAt"       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"       TIMESTAMPTZ,
    "CreatedById"     INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"     INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"       BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"       TIMESTAMPTZ,
    "DeletedById"     INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- BankAccounts
-- -------------------------------------------------------------
CREATE TABLE "BankAccounts" (
    "Id"            SERIAL          PRIMARY KEY,
    "BankName"      VARCHAR(200)    NOT NULL,
    "AccountHolder" VARCHAR(200)    NOT NULL,
    "AccountNumber" VARCHAR(100)    NOT NULL,
    "Branch"        VARCHAR(200),
    "IsPrimary"     BOOLEAN         NOT NULL DEFAULT FALSE,
    "TotalBalance"  NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    "CreatedAt"     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ,
    "CreatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"     BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"     TIMESTAMPTZ,
    "DeletedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- BankAccountCreditLogs
-- -------------------------------------------------------------
CREATE TABLE "BankAccountCreditLogs" (
    "Id"            SERIAL          PRIMARY KEY,
    "BankAccountId" INT             NOT NULL REFERENCES "BankAccounts"("Id") ON DELETE RESTRICT,
    "Amount"        NUMERIC(18, 2)  NOT NULL CHECK ("Amount" > 0),
    "LoggedOn"      DATE            NOT NULL,
    "Remarks"       VARCHAR(500),
    "CreatedAt"     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ,
    "CreatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"     BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"     TIMESTAMPTZ,
    "DeletedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_BankAccountCreditLogs_BankAccountId_LoggedOn"
ON "BankAccountCreditLogs" ("BankAccountId", "LoggedOn" DESC);

-- -------------------------------------------------------------
-- VendorBalanceLogs
-- -------------------------------------------------------------
CREATE TABLE "VendorBalanceLogs" (
    "Id"            SERIAL          PRIMARY KEY,
    "VendorId"      INT             NOT NULL REFERENCES "Vendors"("Id") ON DELETE RESTRICT,
    "BankAccountId" INT             REFERENCES "BankAccounts"("Id") ON DELETE SET NULL,
    "EntryType"     VARCHAR(10)     NOT NULL CHECK ("EntryType" IN ('credit', 'debit')),
    "Amount"        NUMERIC(18, 2)  NOT NULL CHECK ("Amount" > 0),
    "LoggedOn"      DATE            NOT NULL,
    "Remarks"       VARCHAR(500),
    "CreatedAt"     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ,
    "CreatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"     BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"     TIMESTAMPTZ,
    "DeletedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_VendorBalanceLogs_VendorId_LoggedOn"
ON "VendorBalanceLogs" ("VendorId", "LoggedOn" DESC);

-- -------------------------------------------------------------
-- BankAccountDebitLogs
-- -------------------------------------------------------------
CREATE TABLE "BankAccountDebitLogs" (
    "Id"            SERIAL          PRIMARY KEY,
    "BankAccountId" INT             NOT NULL REFERENCES "BankAccounts"("Id") ON DELETE RESTRICT,
    "VendorId"      INT             REFERENCES "Vendors"("Id") ON DELETE SET NULL,
    "Amount"        NUMERIC(18, 2)  NOT NULL CHECK ("Amount" > 0),
    "DebitedOn"     DATE            NOT NULL,
    "Remarks"       VARCHAR(500),
    "CreatedAt"     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ,
    "CreatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"     BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"     TIMESTAMPTZ,
    "DeletedById"   INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_BankAccountDebitLogs_BankAccountId_DebitedOn"
ON "BankAccountDebitLogs" ("BankAccountId", "DebitedOn" DESC);

-- -------------------------------------------------------------
-- PartyBalanceLogs
-- -------------------------------------------------------------
CREATE TABLE "PartyBalanceLogs" (
    "Id"          SERIAL          PRIMARY KEY,
    "PartyNameId" INT             NOT NULL REFERENCES "PartyNames"("Id") ON DELETE RESTRICT,
    "EntryType"   VARCHAR(10)     NOT NULL CHECK ("EntryType" IN ('credit', 'debit')),
    "Amount"      NUMERIC(18, 2)  NOT NULL CHECK ("Amount" > 0),
    "LoggedOn"    DATE            NOT NULL,
    "Remarks"     VARCHAR(500),
    "CreatedAt"   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"   TIMESTAMPTZ,
    "CreatedById" INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById" INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "IsDeleted"   BOOLEAN         NOT NULL DEFAULT FALSE,
    "DeletedOn"   TIMESTAMPTZ,
    "DeletedById" INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_PartyBalanceLogs_PartyNameId_LoggedOn"
ON "PartyBalanceLogs" ("PartyNameId", "LoggedOn" DESC);

-- =============================================================
-- Seed: Admin role
-- =============================================================
INSERT INTO "Roles" ("Name") VALUES ('Admin') ON CONFLICT DO NOTHING;

-- =============================================================
-- Seed: Permissions
-- =============================================================

-- Dashboard
INSERT INTO "Permissions" ("Name", "Description") VALUES ('dashboard.view',          'View the dashboard')                        ON CONFLICT ("Name") DO NOTHING;

-- Extra expenses
INSERT INTO "Permissions" ("Name", "Description") VALUES ('extra_expenses.view',     'View extra expenses')                      ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('extra_expenses.add',      'Add extra expenses')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('extra_expenses.edit',     'Edit extra expenses')                      ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('extra_expenses.delete',   'Delete extra expenses')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('extra_expenses.verify',   'Verify extra expenses')                    ON CONFLICT ("Name") DO NOTHING;

-- Bank accounts
INSERT INTO "Permissions" ("Name", "Description") VALUES ('account_management.view', 'Access account management page')             ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('bank_accounts.view',       'View bank accounts')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('bank_accounts.add',        'Add bank accounts')                        ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('bank_accounts.edit',       'Edit bank accounts')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('bank_accounts.delete',     'Delete bank accounts')                     ON CONFLICT ("Name") DO NOTHING;

-- Users
INSERT INTO "Permissions" ("Name", "Description") VALUES ('users.view',              'View the users list')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('users.add',               'Create a new user')                         ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('users.edit',              'Edit an existing user')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('users.delete',            'Delete a user')                             ON CONFLICT ("Name") DO NOTHING;

-- Transportation
INSERT INTO "Permissions" ("Name", "Description") VALUES ('transportation.view',     'View transportation records')                ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('transportation.add',      'Add a transportation record')                ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('transportation.edit',     'Edit a transportation record')               ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('transportation.delete',   'Delete a transportation record')             ON CONFLICT ("Name") DO NOTHING;

-- Fuel Log
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_log.view',           'View fuel log entries')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_log.add',            'Add a fuel log entry')                      ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_log.edit',           'Edit a fuel log entry')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_log.delete',         'Delete a fuel log entry')                   ON CONFLICT ("Name") DO NOTHING;

-- Dozer Log
INSERT INTO "Permissions" ("Name", "Description") VALUES ('dozer_log.view',          'View dozer log entries')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('dozer_log.add',           'Add a dozer log entry')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('dozer_log.edit',          'Edit a dozer log entry')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('dozer_log.delete',        'Delete a dozer log entry')                  ON CONFLICT ("Name") DO NOTHING;

-- Vehicles
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicles.view',           'View the vehicles list')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicles.add',            'Add a vehicle')                             ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicles.edit',           'Edit a vehicle')                            ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicles.delete',         'Delete a vehicle')                          ON CONFLICT ("Name") DO NOTHING;

-- Materials
INSERT INTO "Permissions" ("Name", "Description") VALUES ('materials.view',          'View the materials list')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('materials.add',           'Add a material')                            ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('materials.edit',          'Edit a material')                           ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('materials.delete',        'Delete a material')                         ON CONFLICT ("Name") DO NOTHING;

-- Vendors
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vendors.view',            'View the vendors list')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vendors.add',             'Add a vendor')                              ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vendors.edit',            'Edit a vendor')                             ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vendors.delete',          'Delete a vendor')                           ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vendor_management.view',  'Access vendor management page')             ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('party_management.view',   'Access party management page')              ON CONFLICT ("Name") DO NOTHING;

-- Projects
INSERT INTO "Permissions" ("Name", "Description") VALUES ('projects.view',           'View the projects list')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('projects.add',            'Add a project')                             ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('projects.edit',           'Edit a project')                            ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('projects.delete',         'Delete a project')                          ON CONFLICT ("Name") DO NOTHING;

-- Project Expenses
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_expenses.view',   'View project expenses')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_expenses.add',    'Add project expenses')                      ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_expenses.edit',   'Edit project expenses')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_expenses.delete', 'Delete project expenses')                   ON CONFLICT ("Name") DO NOTHING;

-- Project Wages
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_wages.view',      'View project wages')                        ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_wages.add',       'Add project wages')                         ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_wages.edit',      'Edit project wages')                        ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_wages.delete',    'Delete project wages')                      ON CONFLICT ("Name") DO NOTHING;

-- Government Offices
INSERT INTO "Permissions" ("Name", "Description") VALUES ('govt_offices.view',       'View government offices')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('govt_offices.add',        'Add government offices')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('govt_offices.edit',       'Edit government offices')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('govt_offices.delete',     'Delete government offices')                 ON CONFLICT ("Name") DO NOTHING;

-- Project Commissions
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_commissions.view','View project commissions')                 ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_commissions.add', 'Add project commissions')                  ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_commissions.edit','Edit project commissions')                 ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('project_commissions.delete','Delete project commissions')               ON CONFLICT ("Name") DO NOTHING;

-- Vehicle Maintenance
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicle_maintenance.view','View vehicle maintenance')                ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicle_maintenance.add', 'Add vehicle maintenance')                 ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicle_maintenance.edit','Edit vehicle maintenance')                ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('vehicle_maintenance.delete','Delete vehicle maintenance')              ON CONFLICT ("Name") DO NOTHING;

-- Maintenance Parts
INSERT INTO "Permissions" ("Name", "Description") VALUES ('maintenance_parts.view', 'View maintenance parts')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('maintenance_parts.add',  'Add maintenance parts')                    ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('maintenance_parts.edit', 'Edit maintenance parts')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('maintenance_parts.delete','Delete maintenance parts')                 ON CONFLICT ("Name") DO NOTHING;

-- Fuel Types
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_types.view',         'View the fuel types list')                  ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_types.add',          'Add a fuel type')                           ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_types.edit',         'Edit a fuel type')                          ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_types.delete',       'Delete a fuel type')                        ON CONFLICT ("Name") DO NOTHING;

-- Roles
INSERT INTO "Permissions" ("Name", "Description") VALUES ('roles.view',              'View the roles list')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('roles.add',               'Create a new role')                         ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('roles.edit',              'Edit an existing role')                     ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('roles.delete',            'Delete a role')                             ON CONFLICT ("Name") DO NOTHING;

-- Permissions
INSERT INTO "Permissions" ("Name", "Description") VALUES ('permissions.view',        'View the permissions list')                 ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('permissions.add',         'Create a new permission')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('permissions.edit',        'Edit an existing permission')               ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('permissions.delete',      'Delete a permission')                       ON CONFLICT ("Name") DO NOTHING;

-- Party Names
INSERT INTO "Permissions" ("Name", "Description") VALUES ('party_names.view',        'View party names')                          ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('party_names.add',         'Add party names')                           ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('party_names.edit',        'Edit party names')                          ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('party_names.delete',      'Delete party names')                        ON CONFLICT ("Name") DO NOTHING;

-- Role Permissions
INSERT INTO "Permissions" ("Name", "Description") VALUES ('role_permissions.view',   'View permissions assigned to roles')        ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('role_permissions.edit',   'Assign or remove permissions from a role')  ON CONFLICT ("Name") DO NOTHING;

-- Monthly Salary
INSERT INTO "Permissions" ("Name", "Description") VALUES ('monthly_salary.view',     'View monthly salary records')               ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('monthly_salary.edit',     'Save or verify a monthly salary record')    ON CONFLICT ("Name") DO NOTHING;

-- Salary Payments
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_payment.view',     'View salary payment records')               ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_payment.add',      'Record a salary payment')                   ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_payment.edit',     'Edit a salary payment record')              ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_payment.delete',   'Delete a salary payment record')            ON CONFLICT ("Name") DO NOTHING;

-- Salary Details
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_detail.view',      'View salary detail summary')                ON CONFLICT ("Name") DO NOTHING;

-- Salary Setup
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_setup.view',       'View salary setup entries')                 ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_setup.add',        'Add a salary entry')                        ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_setup.edit',       'Edit a salary entry')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('salary_setup.delete',     'Delete a salary entry')                     ON CONFLICT ("Name") DO NOTHING;

-- Reports
INSERT INTO "Permissions" ("Name", "Description") VALUES ('transportation_report.view', 'View transportation report')                 ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('fuel_log_report.view',       'View fuel log report')                       ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions" ("Name", "Description") VALUES ('dozer_log_report.view',      'View dozer log report')                      ON CONFLICT ("Name") DO NOTHING;


-- =============================================================
-- Seed: Admin role → assign every permission
-- =============================================================
INSERT INTO "RolePermissions" ("RoleId", "PermissionId")
SELECT r."Id", p."Id"
FROM   "Roles" r
CROSS JOIN "Permissions" p
WHERE  r."Name" = 'Admin'
ON CONFLICT ("RoleId", "PermissionId") DO NOTHING;
