-- =============================================================
-- CMS Full Schema — PostgreSQL / Supabase
-- Run this in Supabase SQL Editor after dropping all tables.
-- =============================================================

-- -------------------------------------------------------------
-- Drop all tables (safe order, CASCADE handles remaining FKs)
-- -------------------------------------------------------------
DROP TABLE IF EXISTS "FuelLogs"       CASCADE;
DROP TABLE IF EXISTS "Transportations" CASCADE;
DROP TABLE IF EXISTS "Materials"      CASCADE;
DROP TABLE IF EXISTS "Vendors"        CASCADE;
DROP TABLE IF EXISTS "Projects"       CASCADE;
DROP TABLE IF EXISTS "Fuels"          CASCADE;
DROP TABLE IF EXISTS "Users"          CASCADE;
DROP TABLE IF EXISTS "Vehicles"       CASCADE;
DROP TABLE IF EXISTS "Roles"          CASCADE;

-- -------------------------------------------------------------
-- Roles  (no dependencies)
-- -------------------------------------------------------------
CREATE TABLE "Roles" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT,
    "UpdatedById"  INT
);

-- -------------------------------------------------------------
-- Vehicles  (CreatedById/UpdatedById FKs added after Users)
-- -------------------------------------------------------------
CREATE TABLE "Vehicles" (
    "Id"           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "NumberPlate"  VARCHAR(20)  NOT NULL,
    "Type"         VARCHAR(20)  NOT NULL CHECK ("Type" IN ('Tipper', 'Jcb')),
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT,
    "UpdatedById"  INT,
    CONSTRAINT "UX_Vehicles_NumberPlate" UNIQUE ("NumberPlate")
);

-- -------------------------------------------------------------
-- Users  (VehicleId / self-ref FKs added after Vehicles)
-- -------------------------------------------------------------
CREATE TABLE "Users" (
    "Id"            SERIAL       PRIMARY KEY,
    "Username"      VARCHAR(50)  NOT NULL,
    "Email"         VARCHAR(256) NOT NULL,
    "PasswordHash"  VARCHAR(500) NOT NULL,
    "FirstName"     VARCHAR(100),
    "LastName"      VARCHAR(100),
    "IsActive"      BOOLEAN      NOT NULL DEFAULT TRUE,
    "CreatedAt"     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ,
    "LastLoginAt"   TIMESTAMPTZ,
    "RoleId"        INT          REFERENCES "Roles"("Id")    ON DELETE SET NULL,
    "VehicleId"     INT,
    "CreatedById"   INT,
    "UpdatedById"   INT,
    CONSTRAINT "UX_Users_Username" UNIQUE ("Username"),
    CONSTRAINT "UX_Users_Email"    UNIQUE ("Email")
);

-- -------------------------------------------------------------
-- Cross-table FKs now that both Vehicles and Users exist
-- -------------------------------------------------------------
ALTER TABLE "Users"
    ADD CONSTRAINT "FK_Users_VehicleId"   FOREIGN KEY ("VehicleId")   REFERENCES "Vehicles"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Users_CreatedById" FOREIGN KEY ("CreatedById")  REFERENCES "Users"("Id")    ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Users_UpdatedById" FOREIGN KEY ("UpdatedById")  REFERENCES "Users"("Id")    ON DELETE SET NULL;

ALTER TABLE "Vehicles"
    ADD CONSTRAINT "FK_Vehicles_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Vehicles_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users"("Id") ON DELETE SET NULL;

ALTER TABLE "Roles"
    ADD CONSTRAINT "FK_Roles_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users"("Id") ON DELETE SET NULL,
    ADD CONSTRAINT "FK_Roles_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users"("Id") ON DELETE SET NULL;

-- -------------------------------------------------------------
-- Materials
-- -------------------------------------------------------------
CREATE TABLE "Materials" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Vendors
-- -------------------------------------------------------------
CREATE TABLE "Vendors" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Projects
-- -------------------------------------------------------------
CREATE TABLE "Projects" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Fuels (fuel types)
-- -------------------------------------------------------------
CREATE TABLE "Fuels" (
    "Id"           SERIAL       PRIMARY KEY,
    "Name"         VARCHAR(100) NOT NULL,
    "CreatedAt"    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Transportations
-- -------------------------------------------------------------
CREATE TABLE "Transportations" (
    "Id"               SERIAL       PRIMARY KEY,
    "TransportedById"  INT          NOT NULL REFERENCES "Users"("Id")    ON DELETE RESTRICT,
    "VehicleId"        INT          REFERENCES "Vehicles"("Id")          ON DELETE SET NULL,
    "VendorId"         INT          REFERENCES "Vendors"("Id")           ON DELETE SET NULL,
    "VendorOther"      VARCHAR(200),
    "ProjectId"        INT          REFERENCES "Projects"("Id")          ON DELETE SET NULL,
    "ProjectOther"     VARCHAR(200),
    "Date"             DATE         NOT NULL,
    "CreatedAt"        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"        TIMESTAMPTZ,
    "CreatedById"      INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"      INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    CONSTRAINT "chk_vendor"  CHECK (("VendorId"  IS NOT NULL) <> ("VendorOther"  IS NOT NULL)),
    CONSTRAINT "chk_project" CHECK (("ProjectId" IS NOT NULL) <> ("ProjectOther" IS NOT NULL))
);

-- -------------------------------------------------------------
-- FuelLogs
-- -------------------------------------------------------------
CREATE TABLE "FuelLogs" (
    "Id"           SERIAL          PRIMARY KEY,
    "DriverId"     INT             NOT NULL REFERENCES "Users"("Id")    ON DELETE RESTRICT,
    "VehicleId"    INT             NOT NULL REFERENCES "Vehicles"("Id") ON DELETE RESTRICT,
    "FuelTypeId"   INT             NOT NULL REFERENCES "Fuels"("Id")    ON DELETE RESTRICT,
    "Quantity"     NUMERIC(10, 2)  NOT NULL CHECK ("Quantity" > 0),
    "Price"        NUMERIC(10, 2)  NOT NULL CHECK ("Price" > 0),
    "Date"         DATE            NOT NULL,
    "CreatedAt"    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMPTZ,
    "CreatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL,
    "UpdatedById"  INT REFERENCES "Users"("Id") ON DELETE SET NULL
);
