-- =============================================================
-- CMS — Local PostgreSQL bootstrap script
-- Creates the "cms" database AND the "Users" table.
--
-- How to run:
--
--   Option A — psql (one command, does everything):
--     psql -U postgres -f database/local_postgres_setup.sql
--
--   Option B — pgAdmin (two clicks):
--     1. Right-click Databases > Create > Database > name: cms > Save
--        (or just run the CREATE DATABASE block below while connected
--         to the default "postgres" database).
--     2. Open Query Tool on the new "cms" database and run the
--        CREATE TABLE / CREATE INDEX block at the bottom.
--
-- The `\gexec` and `\c` lines starting with a backslash are psql
-- meta-commands; pgAdmin treats them as errors and you can ignore
-- them when running each block manually.
-- =============================================================


-- -------------------------------------------------------------
-- 1) Database (run while connected to the default "postgres" DB)
-- -------------------------------------------------------------

SELECT 'CREATE DATABASE cms'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'cms')\gexec


-- -------------------------------------------------------------
-- 2) Switch to the cms database (psql only)
-- -------------------------------------------------------------

\c cms


-- -------------------------------------------------------------
-- 3) Users table + unique indexes (run while connected to "cms")
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Users" (
    "Id"           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"     VARCHAR(50)  NOT NULL,
    "Email"        VARCHAR(256) NOT NULL,
    "PasswordHash" VARCHAR(500) NOT NULL,
    "FirstName"    VARCHAR(100) NULL,
    "LastName"     VARCHAR(100) NULL,
    "IsActive"     BOOLEAN      NOT NULL DEFAULT TRUE,
    "CreatedAt"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMP WITH TIME ZONE NULL,
    "LastLoginAt"  TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Username" ON "Users" ("Username");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Email"    ON "Users" ("Email");
