-- =============================================================
-- CMS — PostgreSQL setup script
-- Target: Supabase / Neon / any PostgreSQL 13+
--
-- The table and column names use PascalCase to match the EF Core
-- defaults, so identifiers are quoted to preserve case in
-- PostgreSQL (which lowercases unquoted identifiers).
--
-- Run this in the Supabase SQL editor (or psql, or pgAdmin) against
-- the database you want to use.
-- =============================================================

CREATE TABLE IF NOT EXISTS "Users" (
    "Id"           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"     VARCHAR(50)  NOT NULL,
    "Email"        VARCHAR(256) NOT NULL,
    "PasswordHash" VARCHAR(500) NOT NULL,
    "FirstName"    VARCHAR(100) NULL,
    "LastName"     VARCHAR(100) NULL,
    "IsActive"     BOOLEAN      NOT NULL DEFAULT TRUE,
    "CreatedAt"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt"    TIMESTAMP WITH TIME ZONE NULL,
    "LastLoginAt"  TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Username" ON "Users" ("Username");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Email"    ON "Users" ("Email");
